services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: system-pite-app
    container_name: system_pite_app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: system_pite
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: system_pite_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: system_pite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
